// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetAccountAccountGetData,
  GetAccountAccountGetResponses,
  GetCopyRatesFromCopyRatesFromGetData,
  GetCopyRatesFromCopyRatesFromGetErrors,
  GetCopyRatesFromCopyRatesFromGetResponses,
  GetCopyRatesRangeCopyRatesRangeGetData,
  GetCopyRatesRangeCopyRatesRangeGetErrors,
  GetCopyRatesRangeCopyRatesRangeGetResponses,
  GetCopyTicksFromCopyTicksFromGetData,
  GetCopyTicksFromCopyTicksFromGetErrors,
  GetCopyTicksFromCopyTicksFromGetResponses,
  GetCopyTicksRangeCopyTicksRangeGetData,
  GetCopyTicksRangeCopyTicksRangeGetErrors,
  GetCopyTicksRangeCopyTicksRangeGetResponses,
  GetHealthHealthGetData,
  GetHealthHealthGetResponses,
  GetHistoryDealsGetHistoryDealsGetGetData,
  GetHistoryDealsGetHistoryDealsGetGetErrors,
  GetHistoryDealsGetHistoryDealsGetGetResponses,
  GetHistoryDealsTotalHistoryDealsTotalGetData,
  GetHistoryDealsTotalHistoryDealsTotalGetErrors,
  GetHistoryDealsTotalHistoryDealsTotalGetResponses,
  GetHistoryHistoryGetData,
  GetHistoryHistoryGetErrors,
  GetHistoryHistoryGetResponses,
  GetHistoryOrdersGetHistoryOrdersGetGetData,
  GetHistoryOrdersGetHistoryOrdersGetGetErrors,
  GetHistoryOrdersGetHistoryOrdersGetGetResponses,
  GetHistoryOrdersTotalHistoryOrdersTotalGetData,
  GetHistoryOrdersTotalHistoryOrdersTotalGetErrors,
  GetHistoryOrdersTotalHistoryOrdersTotalGetResponses,
  GetLastErrorLastErrorGetData,
  GetLastErrorLastErrorGetResponses,
  GetMarketBookGetMarketBookGetGetData,
  GetMarketBookGetMarketBookGetGetErrors,
  GetMarketBookGetMarketBookGetGetResponses,
  GetOhlcOhlcGetData,
  GetOhlcOhlcGetErrors,
  GetOhlcOhlcGetResponses,
  GetOrdersGetOrdersGetGetData,
  GetOrdersGetOrdersGetGetErrors,
  GetOrdersGetOrdersGetGetResponses,
  GetOrdersTotalOrdersTotalGetData,
  GetOrdersTotalOrdersTotalGetResponses,
  GetPositionsGetPositionsGetGetData,
  GetPositionsGetPositionsGetGetErrors,
  GetPositionsGetPositionsGetGetResponses,
  GetPositionsTotalPositionsTotalGetData,
  GetPositionsTotalPositionsTotalGetResponses,
  GetSymbolInfoSymbolInfoGetData,
  GetSymbolInfoSymbolInfoGetErrors,
  GetSymbolInfoSymbolInfoGetResponses,
  GetSymbolsSymbolsGetData,
  GetSymbolsSymbolsGetResponses,
  GetSymbolsTotalSymbolsTotalGetData,
  GetSymbolsTotalSymbolsTotalGetResponses,
  GetTerminalInfoTerminalInfoGetData,
  GetTerminalInfoTerminalInfoGetResponses,
  GetTradesTradesGetData,
  GetTradesTradesGetResponses,
  GetVersionVersionGetData,
  GetVersionVersionGetResponses,
  PostInitializeInitializePostData,
  PostInitializeInitializePostErrors,
  PostInitializeInitializePostResponses,
  PostLoginLoginPostData,
  PostLoginLoginPostErrors,
  PostLoginLoginPostResponses,
  PostMarketBookAddMarketBookAddPostData,
  PostMarketBookAddMarketBookAddPostErrors,
  PostMarketBookAddMarketBookAddPostResponses,
  PostMarketBookReleaseMarketBookReleasePostData,
  PostMarketBookReleaseMarketBookReleasePostErrors,
  PostMarketBookReleaseMarketBookReleasePostResponses,
  PostOrderCalcMarginOrderCalcMarginPostData,
  PostOrderCalcMarginOrderCalcMarginPostErrors,
  PostOrderCalcMarginOrderCalcMarginPostResponses,
  PostOrderCalcProfitOrderCalcProfitPostData,
  PostOrderCalcProfitOrderCalcProfitPostErrors,
  PostOrderCalcProfitOrderCalcProfitPostResponses,
  PostOrderCheckOrderCheckPostData,
  PostOrderCheckOrderCheckPostErrors,
  PostOrderCheckOrderCheckPostResponses,
  PostOrderSendOrderSendPostData,
  PostOrderSendOrderSendPostErrors,
  PostOrderSendOrderSendPostResponses,
  PostShutdownShutdownPostData,
  PostShutdownShutdownPostResponses,
  PostSymbolSelectSymbolSelectPostData,
  PostSymbolSelectSymbolSelectPostErrors,
  PostSymbolSelectSymbolSelectPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Post Initialize
 */
export const postInitializeInitializePost = <ThrowOnError extends boolean = false>(
  options: Options<PostInitializeInitializePostData, ThrowOnError>,
): RequestResult<
  PostInitializeInitializePostResponses,
  PostInitializeInitializePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostInitializeInitializePostResponses,
    PostInitializeInitializePostErrors,
    ThrowOnError
  >({
    url: "/initialize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Login
 */
export const postLoginLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<PostLoginLoginPostData, ThrowOnError>,
): RequestResult<PostLoginLoginPostResponses, PostLoginLoginPostErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostLoginLoginPostResponses,
    PostLoginLoginPostErrors,
    ThrowOnError
  >({
    url: "/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Shutdown
 */
export const postShutdownShutdownPost = <ThrowOnError extends boolean = false>(
  options?: Options<PostShutdownShutdownPostData, ThrowOnError>,
): RequestResult<PostShutdownShutdownPostResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<PostShutdownShutdownPostResponses, unknown, ThrowOnError>({
    url: "/shutdown",
    ...options,
  });

/**
 * Get Version
 */
export const getVersionVersionGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetVersionVersionGetData, ThrowOnError>,
): RequestResult<GetVersionVersionGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetVersionVersionGetResponses, unknown, ThrowOnError>({
    url: "/version",
    ...options,
  });

/**
 * Get Last Error
 */
export const getLastErrorLastErrorGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetLastErrorLastErrorGetData, ThrowOnError>,
): RequestResult<GetLastErrorLastErrorGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetLastErrorLastErrorGetResponses, unknown, ThrowOnError>({
    url: "/last-error",
    ...options,
  });

/**
 * Get Terminal Info
 */
export const getTerminalInfoTerminalInfoGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTerminalInfoTerminalInfoGetData, ThrowOnError>,
): RequestResult<GetTerminalInfoTerminalInfoGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetTerminalInfoTerminalInfoGetResponses, unknown, ThrowOnError>({
    url: "/terminal-info",
    ...options,
  });

/**
 * Get Symbols Total
 */
export const getSymbolsTotalSymbolsTotalGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetSymbolsTotalSymbolsTotalGetData, ThrowOnError>,
): RequestResult<GetSymbolsTotalSymbolsTotalGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetSymbolsTotalSymbolsTotalGetResponses, unknown, ThrowOnError>({
    url: "/symbols-total",
    ...options,
  });

/**
 * Get Symbol Info
 */
export const getSymbolInfoSymbolInfoGet = <ThrowOnError extends boolean = false>(
  options: Options<GetSymbolInfoSymbolInfoGetData, ThrowOnError>,
): RequestResult<
  GetSymbolInfoSymbolInfoGetResponses,
  GetSymbolInfoSymbolInfoGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSymbolInfoSymbolInfoGetResponses,
    GetSymbolInfoSymbolInfoGetErrors,
    ThrowOnError
  >({ url: "/symbol-info", ...options });

/**
 * Post Symbol Select
 */
export const postSymbolSelectSymbolSelectPost = <ThrowOnError extends boolean = false>(
  options: Options<PostSymbolSelectSymbolSelectPostData, ThrowOnError>,
): RequestResult<
  PostSymbolSelectSymbolSelectPostResponses,
  PostSymbolSelectSymbolSelectPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostSymbolSelectSymbolSelectPostResponses,
    PostSymbolSelectSymbolSelectPostErrors,
    ThrowOnError
  >({
    url: "/symbol-select",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Market Book Add
 */
export const postMarketBookAddMarketBookAddPost = <ThrowOnError extends boolean = false>(
  options: Options<PostMarketBookAddMarketBookAddPostData, ThrowOnError>,
): RequestResult<
  PostMarketBookAddMarketBookAddPostResponses,
  PostMarketBookAddMarketBookAddPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostMarketBookAddMarketBookAddPostResponses,
    PostMarketBookAddMarketBookAddPostErrors,
    ThrowOnError
  >({
    url: "/market-book-add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Market Book Get
 */
export const getMarketBookGetMarketBookGetGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMarketBookGetMarketBookGetGetData, ThrowOnError>,
): RequestResult<
  GetMarketBookGetMarketBookGetGetResponses,
  GetMarketBookGetMarketBookGetGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMarketBookGetMarketBookGetGetResponses,
    GetMarketBookGetMarketBookGetGetErrors,
    ThrowOnError
  >({ url: "/market-book-get", ...options });

/**
 * Post Market Book Release
 */
export const postMarketBookReleaseMarketBookReleasePost = <ThrowOnError extends boolean = false>(
  options: Options<PostMarketBookReleaseMarketBookReleasePostData, ThrowOnError>,
): RequestResult<
  PostMarketBookReleaseMarketBookReleasePostResponses,
  PostMarketBookReleaseMarketBookReleasePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostMarketBookReleaseMarketBookReleasePostResponses,
    PostMarketBookReleaseMarketBookReleasePostErrors,
    ThrowOnError
  >({
    url: "/market-book-release",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Ohlc
 */
export const getOhlcOhlcGet = <ThrowOnError extends boolean = false>(
  options: Options<GetOhlcOhlcGetData, ThrowOnError>,
): RequestResult<GetOhlcOhlcGetResponses, GetOhlcOhlcGetErrors, ThrowOnError> =>
  (options.client ?? client).get<GetOhlcOhlcGetResponses, GetOhlcOhlcGetErrors, ThrowOnError>({
    url: "/ohlc",
    ...options,
  });

/**
 * Get Copy Rates From
 */
export const getCopyRatesFromCopyRatesFromGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCopyRatesFromCopyRatesFromGetData, ThrowOnError>,
): RequestResult<
  GetCopyRatesFromCopyRatesFromGetResponses,
  GetCopyRatesFromCopyRatesFromGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCopyRatesFromCopyRatesFromGetResponses,
    GetCopyRatesFromCopyRatesFromGetErrors,
    ThrowOnError
  >({ url: "/copy-rates-from", ...options });

/**
 * Get Copy Rates Range
 */
export const getCopyRatesRangeCopyRatesRangeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCopyRatesRangeCopyRatesRangeGetData, ThrowOnError>,
): RequestResult<
  GetCopyRatesRangeCopyRatesRangeGetResponses,
  GetCopyRatesRangeCopyRatesRangeGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCopyRatesRangeCopyRatesRangeGetResponses,
    GetCopyRatesRangeCopyRatesRangeGetErrors,
    ThrowOnError
  >({ url: "/copy-rates-range", ...options });

/**
 * Get Copy Ticks From
 */
export const getCopyTicksFromCopyTicksFromGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCopyTicksFromCopyTicksFromGetData, ThrowOnError>,
): RequestResult<
  GetCopyTicksFromCopyTicksFromGetResponses,
  GetCopyTicksFromCopyTicksFromGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCopyTicksFromCopyTicksFromGetResponses,
    GetCopyTicksFromCopyTicksFromGetErrors,
    ThrowOnError
  >({ url: "/copy-ticks-from", ...options });

/**
 * Get Copy Ticks Range
 */
export const getCopyTicksRangeCopyTicksRangeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCopyTicksRangeCopyTicksRangeGetData, ThrowOnError>,
): RequestResult<
  GetCopyTicksRangeCopyTicksRangeGetResponses,
  GetCopyTicksRangeCopyTicksRangeGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCopyTicksRangeCopyTicksRangeGetResponses,
    GetCopyTicksRangeCopyTicksRangeGetErrors,
    ThrowOnError
  >({ url: "/copy-ticks-range", ...options });

/**
 * Get Orders Total
 */
export const getOrdersTotalOrdersTotalGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersTotalOrdersTotalGetData, ThrowOnError>,
): RequestResult<GetOrdersTotalOrdersTotalGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetOrdersTotalOrdersTotalGetResponses, unknown, ThrowOnError>({
    url: "/orders-total",
    ...options,
  });

/**
 * Get Orders Get
 */
export const getOrdersGetOrdersGetGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetOrdersGetOrdersGetGetData, ThrowOnError>,
): RequestResult<GetOrdersGetOrdersGetGetResponses, GetOrdersGetOrdersGetGetErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetOrdersGetOrdersGetGetResponses,
    GetOrdersGetOrdersGetGetErrors,
    ThrowOnError
  >({ url: "/orders-get", ...options });

/**
 * Post Order Calc Margin
 */
export const postOrderCalcMarginOrderCalcMarginPost = <ThrowOnError extends boolean = false>(
  options: Options<PostOrderCalcMarginOrderCalcMarginPostData, ThrowOnError>,
): RequestResult<
  PostOrderCalcMarginOrderCalcMarginPostResponses,
  PostOrderCalcMarginOrderCalcMarginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostOrderCalcMarginOrderCalcMarginPostResponses,
    PostOrderCalcMarginOrderCalcMarginPostErrors,
    ThrowOnError
  >({
    url: "/order-calc-margin",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Order Calc Profit
 */
export const postOrderCalcProfitOrderCalcProfitPost = <ThrowOnError extends boolean = false>(
  options: Options<PostOrderCalcProfitOrderCalcProfitPostData, ThrowOnError>,
): RequestResult<
  PostOrderCalcProfitOrderCalcProfitPostResponses,
  PostOrderCalcProfitOrderCalcProfitPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostOrderCalcProfitOrderCalcProfitPostResponses,
    PostOrderCalcProfitOrderCalcProfitPostErrors,
    ThrowOnError
  >({
    url: "/order-calc-profit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Order Check
 */
export const postOrderCheckOrderCheckPost = <ThrowOnError extends boolean = false>(
  options: Options<PostOrderCheckOrderCheckPostData, ThrowOnError>,
): RequestResult<
  PostOrderCheckOrderCheckPostResponses,
  PostOrderCheckOrderCheckPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostOrderCheckOrderCheckPostResponses,
    PostOrderCheckOrderCheckPostErrors,
    ThrowOnError
  >({
    url: "/order-check",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Post Order Send
 */
export const postOrderSendOrderSendPost = <ThrowOnError extends boolean = false>(
  options: Options<PostOrderSendOrderSendPostData, ThrowOnError>,
): RequestResult<
  PostOrderSendOrderSendPostResponses,
  PostOrderSendOrderSendPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostOrderSendOrderSendPostResponses,
    PostOrderSendOrderSendPostErrors,
    ThrowOnError
  >({
    url: "/order-send",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Positions Total
 */
export const getPositionsTotalPositionsTotalGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPositionsTotalPositionsTotalGetData, ThrowOnError>,
): RequestResult<GetPositionsTotalPositionsTotalGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetPositionsTotalPositionsTotalGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/positions-total", ...options });

/**
 * Get Positions Get
 */
export const getPositionsGetPositionsGetGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPositionsGetPositionsGetGetData, ThrowOnError>,
): RequestResult<
  GetPositionsGetPositionsGetGetResponses,
  GetPositionsGetPositionsGetGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetPositionsGetPositionsGetGetResponses,
    GetPositionsGetPositionsGetGetErrors,
    ThrowOnError
  >({ url: "/positions-get", ...options });

/**
 * Get History Orders Total
 */
export const getHistoryOrdersTotalHistoryOrdersTotalGet = <ThrowOnError extends boolean = false>(
  options: Options<GetHistoryOrdersTotalHistoryOrdersTotalGetData, ThrowOnError>,
): RequestResult<
  GetHistoryOrdersTotalHistoryOrdersTotalGetResponses,
  GetHistoryOrdersTotalHistoryOrdersTotalGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetHistoryOrdersTotalHistoryOrdersTotalGetResponses,
    GetHistoryOrdersTotalHistoryOrdersTotalGetErrors,
    ThrowOnError
  >({ url: "/history-orders-total", ...options });

/**
 * Get History Orders Get
 */
export const getHistoryOrdersGetHistoryOrdersGetGet = <ThrowOnError extends boolean = false>(
  options: Options<GetHistoryOrdersGetHistoryOrdersGetGetData, ThrowOnError>,
): RequestResult<
  GetHistoryOrdersGetHistoryOrdersGetGetResponses,
  GetHistoryOrdersGetHistoryOrdersGetGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetHistoryOrdersGetHistoryOrdersGetGetResponses,
    GetHistoryOrdersGetHistoryOrdersGetGetErrors,
    ThrowOnError
  >({ url: "/history-orders-get", ...options });

/**
 * Get History Deals Total
 */
export const getHistoryDealsTotalHistoryDealsTotalGet = <ThrowOnError extends boolean = false>(
  options: Options<GetHistoryDealsTotalHistoryDealsTotalGetData, ThrowOnError>,
): RequestResult<
  GetHistoryDealsTotalHistoryDealsTotalGetResponses,
  GetHistoryDealsTotalHistoryDealsTotalGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetHistoryDealsTotalHistoryDealsTotalGetResponses,
    GetHistoryDealsTotalHistoryDealsTotalGetErrors,
    ThrowOnError
  >({ url: "/history-deals-total", ...options });

/**
 * Get History Deals Get
 */
export const getHistoryDealsGetHistoryDealsGetGet = <ThrowOnError extends boolean = false>(
  options: Options<GetHistoryDealsGetHistoryDealsGetGetData, ThrowOnError>,
): RequestResult<
  GetHistoryDealsGetHistoryDealsGetGetResponses,
  GetHistoryDealsGetHistoryDealsGetGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetHistoryDealsGetHistoryDealsGetGetResponses,
    GetHistoryDealsGetHistoryDealsGetGetErrors,
    ThrowOnError
  >({ url: "/history-deals-get", ...options });

/**
 * Get Trades
 */
export const getTradesTradesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTradesTradesGetData, ThrowOnError>,
): RequestResult<GetTradesTradesGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetTradesTradesGetResponses, unknown, ThrowOnError>({
    url: "/trades",
    ...options,
  });

/**
 * Get Account
 */
export const getAccountAccountGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAccountAccountGetData, ThrowOnError>,
): RequestResult<GetAccountAccountGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetAccountAccountGetResponses, unknown, ThrowOnError>({
    url: "/account",
    ...options,
  });

/**
 * Get History
 */
export const getHistoryHistoryGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetHistoryHistoryGetData, ThrowOnError>,
): RequestResult<GetHistoryHistoryGetResponses, GetHistoryHistoryGetErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetHistoryHistoryGetResponses,
    GetHistoryHistoryGetErrors,
    ThrowOnError
  >({ url: "/history", ...options });

/**
 * Get Symbols
 */
export const getSymbolsSymbolsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetSymbolsSymbolsGetData, ThrowOnError>,
): RequestResult<GetSymbolsSymbolsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetSymbolsSymbolsGetResponses, unknown, ThrowOnError>({
    url: "/symbols",
    ...options,
  });

/**
 * Get Health
 */
export const getHealthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthHealthGetData, ThrowOnError>,
): RequestResult<GetHealthHealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthHealthGetResponses, unknown, ThrowOnError>({
    url: "/health",
    ...options,
  });
