// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://scripts` | (string & {});
};

/**
 * AccountResponse
 */
export type AccountResponse = {
  /**
   * Login
   *
   * Account login number
   */
  login: number;
  /**
   * Balance
   *
   * Account balance
   */
  balance: number;
  /**
   * Equity
   *
   * Account equity
   */
  equity: number;
  /**
   * Margin
   *
   * Used margin
   */
  margin: number;
  /**
   * Marginfree
   *
   * Free margin
   */
  marginFree: number;
  /**
   * Profit
   *
   * Current profit
   */
  profit: number;
  /**
   * Leverage
   *
   * Account leverage
   */
  leverage: number;
  /**
   * Server
   *
   * Trade server name
   */
  server: string;
  /**
   * Currency
   *
   * Deposit currency
   */
  currency: string;
  /**
   * Name
   *
   * Account owner name
   */
  name: string;
  /**
   * Trademode
   *
   * Trade mode (0=real, 1=demo)
   */
  tradeMode: number;
  /**
   * Marginlevel
   *
   * Margin level percentage
   */
  marginLevel: number;
};

/**
 * CalcMarginResponse
 */
export type CalcMarginResponse = {
  /**
   * Margin
   *
   * Required margin
   */
  margin: number;
};

/**
 * CalcProfitResponse
 */
export type CalcProfitResponse = {
  /**
   * Profit
   *
   * Calculated profit
   */
  profit: number;
};

/**
 * Candle
 */
export type Candle = {
  /**
   * Time
   *
   * Unix timestamp in seconds
   */
  time: number;
  /**
   * Open
   *
   * Open price
   */
  open: number;
  /**
   * High
   *
   * High price
   */
  high: number;
  /**
   * Low
   *
   * Low price
   */
  low: number;
  /**
   * Close
   *
   * Close price
   */
  close: number;
  /**
   * Tickvolume
   *
   * Tick volume
   */
  tickVolume: number;
  /**
   * Spread
   *
   * Spread in points
   */
  spread: number;
  /**
   * Realvolume
   *
   * Real volume
   */
  realVolume: number;
};

/**
 * CheckResult
 */
export type CheckResult = {
  /**
   * Retcode
   *
   * Return code
   */
  retcode: number;
  /**
   * Balance
   *
   * Balance after check
   */
  balance: number;
  /**
   * Equity
   *
   * Equity after check
   */
  equity: number;
  /**
   * Profit
   *
   * Floating profit
   */
  profit: number;
  /**
   * Margin
   *
   * Margin required
   */
  margin: number;
  /**
   * Margin Free
   *
   * Free margin
   */
  margin_free: number;
  /**
   * Margin Level
   *
   * Margin level
   */
  margin_level: number;
  /**
   * Comment
   *
   * Server comment
   */
  comment: string;
  /**
   * Request
   *
   * Original request
   */
  request: {
    [key: string]: unknown;
  };
};

/**
 * CopyRatesResponse
 */
export type CopyRatesResponse = {
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Timeframe
   *
   * Timeframe string
   */
  timeframe: string;
  /**
   * Candles
   *
   * OHLC candles
   */
  candles: Array<Candle>;
};

/**
 * CopyTicksResponse
 */
export type CopyTicksResponse = {
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Ticks
   *
   * Tick data
   */
  ticks: Array<Tick>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
  /**
   * Status
   *
   * API status
   */
  status: string;
  /**
   * Mt5
   *
   * MT5 connection status
   */
  mt5: string;
  /**
   * Terminal
   *
   * Terminal running status
   */
  terminal: string;
  /**
   * Account
   *
   * Account login number or null
   */
  account: number | null;
};

/**
 * HistoryDeal
 */
export type HistoryDeal = {
  /**
   * Ticket
   *
   * Deal ticket number
   */
  ticket: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Type
   *
   * Deal type: buy or sell
   */
  type: string;
  /**
   * Volume
   *
   * Deal volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Deal price
   */
  price: number;
  /**
   * Profit
   *
   * Profit in deposit currency
   */
  profit: number;
  /**
   * Commission
   *
   * Commission charged
   */
  commission: number;
  /**
   * Swap
   *
   * Swap charged
   */
  swap: number;
  /**
   * Time
   *
   * Deal time (unix seconds)
   */
  time: number;
  /**
   * Comment
   *
   * Comment
   */
  comment: string;
  /**
   * Magic
   *
   * Expert Advisor ID
   */
  magic: number;
};

/**
 * HistoryOrder
 */
export type HistoryOrder = {
  /**
   * Ticket
   *
   * Order ticket number
   */
  ticket: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Type
   *
   * Order type description
   */
  type: string;
  /**
   * Volume
   *
   * Order volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Order price
   */
  price: number;
  /**
   * Sl
   *
   * Stop Loss level
   */
  sl: number;
  /**
   * Tp
   *
   * Take Profit level
   */
  tp: number;
  /**
   * Time
   *
   * Order time (unix seconds)
   */
  time: number;
  /**
   * Comment
   *
   * Comment
   */
  comment: string;
  /**
   * Magic
   *
   * Expert Advisor ID
   */
  magic: number;
};

/**
 * HistoryResponse
 */
export type HistoryResponse = {
  /**
   * Deals
   *
   * Historical deals
   */
  deals: Array<HistoryDeal>;
  /**
   * Orders
   *
   * Historical orders
   */
  orders: Array<HistoryOrder>;
};

/**
 * InitializeRequest
 */
export type InitializeRequest = {
  /**
   * Path
   *
   * Terminal executable path
   */
  path?: string | null;
  /**
   * Login
   *
   * Account login
   */
  login?: number | null;
  /**
   * Password
   *
   * Account password
   */
  password?: string | null;
  /**
   * Server
   *
   * Trade server
   */
  server?: string | null;
  /**
   * Timeout
   *
   * Connection timeout (ms)
   */
  timeout?: number | null;
  /**
   * Portable
   *
   * Portable mode
   */
  portable?: boolean | null;
};

/**
 * InitializeResponse
 */
export type InitializeResponse = {
  /**
   * Result
   *
   * Initialization result
   */
  result: boolean;
};

/**
 * LastErrorResponse
 */
export type LastErrorResponse = {
  /**
   * Code
   *
   * Error code
   */
  code: number;
  /**
   * Description
   *
   * Error description
   */
  description: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Login
   *
   * Account login
   */
  login: number;
  /**
   * Password
   *
   * Account password
   */
  password?: string | null;
  /**
   * Server
   *
   * Trade server
   */
  server?: string | null;
  /**
   * Timeout
   *
   * Connection timeout (ms)
   */
  timeout?: number | null;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
  /**
   * Result
   *
   * Login result
   */
  result: boolean;
};

/**
 * MarketBookActionResponse
 */
export type MarketBookActionResponse = {
  /**
   * Result
   *
   * Operation result
   */
  result: boolean;
};

/**
 * MarketBookEntry
 */
export type MarketBookEntry = {
  /**
   * Type
   *
   * Book type
   */
  type: number;
  /**
   * Price
   *
   * Price
   */
  price: number;
  /**
   * Volume
   *
   * Volume
   */
  volume: number;
  /**
   * Volume Dbl
   *
   * Volume (double precision)
   */
  volume_dbl: number;
};

/**
 * MarketBookResponse
 */
export type MarketBookResponse = {
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Book
   *
   * Market depth entries
   */
  book: Array<MarketBookEntry>;
};

/**
 * OHLCResponse
 */
export type OhlcResponse = {
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Timeframe
   *
   * Timeframe string
   */
  timeframe: string;
  /**
   * Candles
   *
   * OHLC candles
   */
  candles: Array<Candle>;
};

/**
 * Order
 */
export type Order = {
  /**
   * Ticket
   *
   * Order ticket number
   */
  ticket: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Type
   *
   * Order type description
   */
  type: string;
  /**
   * Volume
   *
   * Order volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Order price
   */
  price: number;
  /**
   * Sl
   *
   * Stop Loss level
   */
  sl: number;
  /**
   * Tp
   *
   * Take Profit level
   */
  tp: number;
  /**
   * Opentime
   *
   * Order open time (unix seconds)
   */
  openTime: number;
  /**
   * Comment
   *
   * Comment
   */
  comment: string;
  /**
   * Magic
   *
   * Expert Advisor ID
   */
  magic: number;
};

/**
 * OrderCalcMarginRequest
 */
export type OrderCalcMarginRequest = {
  /**
   * Action
   *
   * Trade operation type (ORDER_TYPE_*)
   */
  action: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Volume
   *
   * Volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Price
   */
  price: number;
};

/**
 * OrderCalcProfitRequest
 */
export type OrderCalcProfitRequest = {
  /**
   * Action
   *
   * Trade operation type (ORDER_TYPE_*)
   */
  action: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Volume
   *
   * Volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Price
   */
  price: number;
  /**
   * Price Close
   *
   * Close price
   */
  price_close: number;
};

/**
 * Position
 */
export type Position = {
  /**
   * Ticket
   *
   * Position ticket number
   */
  ticket: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Type
   *
   * Position type: buy or sell
   */
  type: string;
  /**
   * Volume
   *
   * Position volume in lots
   */
  volume: number;
  /**
   * Priceopen
   *
   * Open price
   */
  priceOpen: number;
  /**
   * Pricecurrent
   *
   * Current price
   */
  priceCurrent: number;
  /**
   * Profit
   *
   * Profit in deposit currency
   */
  profit: number;
  /**
   * Swap
   *
   * Swap charged
   */
  swap: number;
  /**
   * Commission
   *
   * Commission charged
   */
  commission: number;
  /**
   * Sl
   *
   * Stop Loss level
   */
  sl: number;
  /**
   * Tp
   *
   * Take Profit level
   */
  tp: number;
  /**
   * Opentime
   *
   * Position open time (unix seconds)
   */
  openTime: number;
  /**
   * Comment
   *
   * Comment
   */
  comment: string;
};

/**
 * ShutdownResponse
 */
export type ShutdownResponse = {
  /**
   * Result
   *
   * Shutdown result
   */
  result: boolean;
};

/**
 * SymbolInfo
 */
export type SymbolInfo = {
  /**
   * Name
   *
   * Symbol name
   */
  name: string;
  /**
   * Bid
   *
   * Current bid price
   */
  bid: number;
  /**
   * Ask
   *
   * Current ask price
   */
  ask: number;
  /**
   * Spread
   *
   * Spread in points
   */
  spread: number;
  /**
   * Digits
   *
   * Digits after decimal point
   */
  digits: number;
  /**
   * Trademode
   *
   * Trade mode
   */
  tradeMode: number;
  /**
   * Volumemin
   *
   * Minimum volume
   */
  volumeMin: number;
  /**
   * Volumemax
   *
   * Maximum volume
   */
  volumeMax: number;
  /**
   * Volumestep
   *
   * Volume step
   */
  volumeStep: number;
};

/**
 * SymbolInfoFullResponse
 */
export type SymbolInfoFullResponse = {
  /**
   * Info
   *
   * Full symbol information
   */
  info: {
    [key: string]: unknown;
  };
};

/**
 * SymbolSelectRequest
 */
export type SymbolSelectRequest = {
  /**
   * Symbol
   *
   * Symbol name to enable/disable
   */
  symbol: string;
  /**
   * Enable
   *
   * Enable or disable symbol
   */
  enable?: boolean;
};

/**
 * SymbolSelectResponse
 */
export type SymbolSelectResponse = {
  /**
   * Result
   *
   * Operation result
   */
  result: boolean;
};

/**
 * SymbolsResponse
 */
export type SymbolsResponse = {
  /**
   * Symbols
   *
   * Available symbols
   */
  symbols: Array<SymbolInfo>;
};

/**
 * TerminalInfoResponse
 */
export type TerminalInfoResponse = {
  /**
   * Info
   *
   * Full terminal information
   */
  info: {
    [key: string]: unknown;
  };
};

/**
 * Tick
 */
export type Tick = {
  /**
   * Time
   *
   * Tick time (unix seconds)
   */
  time: number;
  /**
   * Bid
   *
   * Bid price
   */
  bid: number;
  /**
   * Ask
   *
   * Ask price
   */
  ask: number;
  /**
   * Last
   *
   * Last price
   */
  last: number;
  /**
   * Volume
   *
   * Volume
   */
  volume: number;
  /**
   * Time Msc
   *
   * Tick time (milliseconds)
   */
  time_msc: number;
  /**
   * Flags
   *
   * Tick flags
   */
  flags: number;
  /**
   * Volume Real
   *
   * Volume (double precision)
   */
  volume_real: number;
};

/**
 * TotalResponse
 */
export type TotalResponse = {
  /**
   * Total
   *
   * Total count
   */
  total: number;
};

/**
 * TradeRequest
 */
export type TradeRequest = {
  /**
   * Action
   *
   * Trade operation type
   */
  action: number;
  /**
   * Symbol
   *
   * Symbol name
   */
  symbol: string;
  /**
   * Volume
   *
   * Volume in lots
   */
  volume: number;
  /**
   * Price
   *
   * Price
   */
  price: number;
  /**
   * Sl
   *
   * Stop Loss
   */
  sl?: number;
  /**
   * Tp
   *
   * Take Profit
   */
  tp?: number;
  /**
   * Deviation
   *
   * Deviation
   */
  deviation?: number;
  /**
   * Magic
   *
   * Expert Advisor ID
   */
  magic?: number;
  /**
   * Comment
   *
   * Comment
   */
  comment?: string;
  /**
   * Type Time
   *
   * Order expiration type
   */
  type_time?: number;
  /**
   * Type Filling
   *
   * Order filling type
   */
  type_filling?: number;
  /**
   * Position
   *
   * Position ticket
   */
  position?: number;
  /**
   * Position By
   *
   * Opposite position
   */
  position_by?: number;
};

/**
 * TradeResult
 */
export type TradeResult = {
  /**
   * Retcode
   *
   * Return code
   */
  retcode: number;
  /**
   * Deal
   *
   * Deal ticket
   */
  deal: number;
  /**
   * Order
   *
   * Order ticket
   */
  order: number;
  /**
   * Volume
   *
   * Deal volume
   */
  volume: number;
  /**
   * Price
   *
   * Deal price
   */
  price: number;
  /**
   * Bid
   *
   * Current bid
   */
  bid: number;
  /**
   * Ask
   *
   * Current ask
   */
  ask: number;
  /**
   * Comment
   *
   * Server comment
   */
  comment: string;
  /**
   * Request
   *
   * Original request
   */
  request: {
    [key: string]: unknown;
  };
};

/**
 * TradesResponse
 */
export type TradesResponse = {
  /**
   * Positions
   *
   * Open positions
   */
  positions: Array<Position>;
  /**
   * Orders
   *
   * Pending orders
   */
  orders: Array<Order>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * VersionResponse
 */
export type VersionResponse = {
  /**
   * Major
   *
   * Major version
   */
  major: number;
  /**
   * Minor
   *
   * Minor version
   */
  minor: number;
  /**
   * Build
   *
   * Build number
   */
  build: number;
  /**
   * Release Date
   *
   * Release date (unix timestamp)
   */
  release_date: number;
};

export type PostInitializeInitializePostData = {
  body: InitializeRequest;
  path?: never;
  query?: never;
  url: "/initialize";
};

export type PostInitializeInitializePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostInitializeInitializePostError =
  PostInitializeInitializePostErrors[keyof PostInitializeInitializePostErrors];

export type PostInitializeInitializePostResponses = {
  /**
   * Successful Response
   */
  200: InitializeResponse;
};

export type PostInitializeInitializePostResponse =
  PostInitializeInitializePostResponses[keyof PostInitializeInitializePostResponses];

export type PostLoginLoginPostData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/login";
};

export type PostLoginLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostLoginLoginPostError = PostLoginLoginPostErrors[keyof PostLoginLoginPostErrors];

export type PostLoginLoginPostResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type PostLoginLoginPostResponse =
  PostLoginLoginPostResponses[keyof PostLoginLoginPostResponses];

export type PostShutdownShutdownPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/shutdown";
};

export type PostShutdownShutdownPostResponses = {
  /**
   * Successful Response
   */
  200: ShutdownResponse;
};

export type PostShutdownShutdownPostResponse =
  PostShutdownShutdownPostResponses[keyof PostShutdownShutdownPostResponses];

export type GetVersionVersionGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/version";
};

export type GetVersionVersionGetResponses = {
  /**
   * Successful Response
   */
  200: VersionResponse;
};

export type GetVersionVersionGetResponse =
  GetVersionVersionGetResponses[keyof GetVersionVersionGetResponses];

export type GetLastErrorLastErrorGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/last-error";
};

export type GetLastErrorLastErrorGetResponses = {
  /**
   * Successful Response
   */
  200: LastErrorResponse;
};

export type GetLastErrorLastErrorGetResponse =
  GetLastErrorLastErrorGetResponses[keyof GetLastErrorLastErrorGetResponses];

export type GetTerminalInfoTerminalInfoGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/terminal-info";
};

export type GetTerminalInfoTerminalInfoGetResponses = {
  /**
   * Successful Response
   */
  200: TerminalInfoResponse;
};

export type GetTerminalInfoTerminalInfoGetResponse =
  GetTerminalInfoTerminalInfoGetResponses[keyof GetTerminalInfoTerminalInfoGetResponses];

export type GetSymbolsTotalSymbolsTotalGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/symbols-total";
};

export type GetSymbolsTotalSymbolsTotalGetResponses = {
  /**
   * Successful Response
   */
  200: TotalResponse;
};

export type GetSymbolsTotalSymbolsTotalGetResponse =
  GetSymbolsTotalSymbolsTotalGetResponses[keyof GetSymbolsTotalSymbolsTotalGetResponses];

export type GetSymbolInfoSymbolInfoGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
  };
  url: "/symbol-info";
};

export type GetSymbolInfoSymbolInfoGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSymbolInfoSymbolInfoGetError =
  GetSymbolInfoSymbolInfoGetErrors[keyof GetSymbolInfoSymbolInfoGetErrors];

export type GetSymbolInfoSymbolInfoGetResponses = {
  /**
   * Successful Response
   */
  200: SymbolInfoFullResponse;
};

export type GetSymbolInfoSymbolInfoGetResponse =
  GetSymbolInfoSymbolInfoGetResponses[keyof GetSymbolInfoSymbolInfoGetResponses];

export type PostSymbolSelectSymbolSelectPostData = {
  body: SymbolSelectRequest;
  path?: never;
  query?: never;
  url: "/symbol-select";
};

export type PostSymbolSelectSymbolSelectPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostSymbolSelectSymbolSelectPostError =
  PostSymbolSelectSymbolSelectPostErrors[keyof PostSymbolSelectSymbolSelectPostErrors];

export type PostSymbolSelectSymbolSelectPostResponses = {
  /**
   * Successful Response
   */
  200: SymbolSelectResponse;
};

export type PostSymbolSelectSymbolSelectPostResponse =
  PostSymbolSelectSymbolSelectPostResponses[keyof PostSymbolSelectSymbolSelectPostResponses];

export type PostMarketBookAddMarketBookAddPostData = {
  body: SymbolSelectRequest;
  path?: never;
  query?: never;
  url: "/market-book-add";
};

export type PostMarketBookAddMarketBookAddPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostMarketBookAddMarketBookAddPostError =
  PostMarketBookAddMarketBookAddPostErrors[keyof PostMarketBookAddMarketBookAddPostErrors];

export type PostMarketBookAddMarketBookAddPostResponses = {
  /**
   * Successful Response
   */
  200: MarketBookActionResponse;
};

export type PostMarketBookAddMarketBookAddPostResponse =
  PostMarketBookAddMarketBookAddPostResponses[keyof PostMarketBookAddMarketBookAddPostResponses];

export type GetMarketBookGetMarketBookGetGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
  };
  url: "/market-book-get";
};

export type GetMarketBookGetMarketBookGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetMarketBookGetMarketBookGetGetError =
  GetMarketBookGetMarketBookGetGetErrors[keyof GetMarketBookGetMarketBookGetGetErrors];

export type GetMarketBookGetMarketBookGetGetResponses = {
  /**
   * Successful Response
   */
  200: MarketBookResponse;
};

export type GetMarketBookGetMarketBookGetGetResponse =
  GetMarketBookGetMarketBookGetGetResponses[keyof GetMarketBookGetMarketBookGetGetResponses];

export type PostMarketBookReleaseMarketBookReleasePostData = {
  body: SymbolSelectRequest;
  path?: never;
  query?: never;
  url: "/market-book-release";
};

export type PostMarketBookReleaseMarketBookReleasePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostMarketBookReleaseMarketBookReleasePostError =
  PostMarketBookReleaseMarketBookReleasePostErrors[keyof PostMarketBookReleaseMarketBookReleasePostErrors];

export type PostMarketBookReleaseMarketBookReleasePostResponses = {
  /**
   * Successful Response
   */
  200: MarketBookActionResponse;
};

export type PostMarketBookReleaseMarketBookReleasePostResponse =
  PostMarketBookReleaseMarketBookReleasePostResponses[keyof PostMarketBookReleaseMarketBookReleasePostResponses];

export type GetOhlcOhlcGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name, e.g. EURUSD
     */
    symbol: string;
    /**
     * Timeframe
     *
     * Timeframe: M1, M5, M15, H1, H4, D1
     */
    timeframe?: string;
    /**
     * Count
     *
     * Number of candles
     */
    count?: number;
  };
  url: "/ohlc";
};

export type GetOhlcOhlcGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOhlcOhlcGetError = GetOhlcOhlcGetErrors[keyof GetOhlcOhlcGetErrors];

export type GetOhlcOhlcGetResponses = {
  /**
   * Successful Response
   */
  200: OhlcResponse;
};

export type GetOhlcOhlcGetResponse = GetOhlcOhlcGetResponses[keyof GetOhlcOhlcGetResponses];

export type GetCopyRatesFromCopyRatesFromGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
    /**
     * Timeframe
     *
     * Timeframe: M1, M5, M15, H1, H4, D1
     */
    timeframe: string;
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Count
     *
     * Number of candles
     */
    count?: number;
  };
  url: "/copy-rates-from";
};

export type GetCopyRatesFromCopyRatesFromGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCopyRatesFromCopyRatesFromGetError =
  GetCopyRatesFromCopyRatesFromGetErrors[keyof GetCopyRatesFromCopyRatesFromGetErrors];

export type GetCopyRatesFromCopyRatesFromGetResponses = {
  /**
   * Successful Response
   */
  200: CopyRatesResponse;
};

export type GetCopyRatesFromCopyRatesFromGetResponse =
  GetCopyRatesFromCopyRatesFromGetResponses[keyof GetCopyRatesFromCopyRatesFromGetResponses];

export type GetCopyRatesRangeCopyRatesRangeGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
    /**
     * Timeframe
     *
     * Timeframe: M1, M5, M15, H1, H4, D1
     */
    timeframe: string;
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
  };
  url: "/copy-rates-range";
};

export type GetCopyRatesRangeCopyRatesRangeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCopyRatesRangeCopyRatesRangeGetError =
  GetCopyRatesRangeCopyRatesRangeGetErrors[keyof GetCopyRatesRangeCopyRatesRangeGetErrors];

export type GetCopyRatesRangeCopyRatesRangeGetResponses = {
  /**
   * Successful Response
   */
  200: CopyRatesResponse;
};

export type GetCopyRatesRangeCopyRatesRangeGetResponse =
  GetCopyRatesRangeCopyRatesRangeGetResponses[keyof GetCopyRatesRangeCopyRatesRangeGetResponses];

export type GetCopyTicksFromCopyTicksFromGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Count
     *
     * Number of ticks
     */
    count?: number;
    /**
     * Flags
     *
     * Tick flags (COPY_TICKS_ALL=0, INFO=1, TRADE=2)
     */
    flags?: number;
  };
  url: "/copy-ticks-from";
};

export type GetCopyTicksFromCopyTicksFromGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCopyTicksFromCopyTicksFromGetError =
  GetCopyTicksFromCopyTicksFromGetErrors[keyof GetCopyTicksFromCopyTicksFromGetErrors];

export type GetCopyTicksFromCopyTicksFromGetResponses = {
  /**
   * Successful Response
   */
  200: CopyTicksResponse;
};

export type GetCopyTicksFromCopyTicksFromGetResponse =
  GetCopyTicksFromCopyTicksFromGetResponses[keyof GetCopyTicksFromCopyTicksFromGetResponses];

export type GetCopyTicksRangeCopyTicksRangeGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Symbol
     *
     * Symbol name
     */
    symbol: string;
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
    /**
     * Flags
     *
     * Tick flags (COPY_TICKS_ALL=0, INFO=1, TRADE=2)
     */
    flags?: number;
  };
  url: "/copy-ticks-range";
};

export type GetCopyTicksRangeCopyTicksRangeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCopyTicksRangeCopyTicksRangeGetError =
  GetCopyTicksRangeCopyTicksRangeGetErrors[keyof GetCopyTicksRangeCopyTicksRangeGetErrors];

export type GetCopyTicksRangeCopyTicksRangeGetResponses = {
  /**
   * Successful Response
   */
  200: CopyTicksResponse;
};

export type GetCopyTicksRangeCopyTicksRangeGetResponse =
  GetCopyTicksRangeCopyTicksRangeGetResponses[keyof GetCopyTicksRangeCopyTicksRangeGetResponses];

export type GetOrdersTotalOrdersTotalGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/orders-total";
};

export type GetOrdersTotalOrdersTotalGetResponses = {
  /**
   * Successful Response
   */
  200: TotalResponse;
};

export type GetOrdersTotalOrdersTotalGetResponse =
  GetOrdersTotalOrdersTotalGetResponses[keyof GetOrdersTotalOrdersTotalGetResponses];

export type GetOrdersGetOrdersGetGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Symbol
     *
     * Filter by symbol
     */
    symbol?: string | null;
    /**
     * Group
     *
     * Filter by group pattern
     */
    group?: string | null;
    /**
     * Ticket
     *
     * Filter by ticket
     */
    ticket?: number | null;
  };
  url: "/orders-get";
};

export type GetOrdersGetOrdersGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrdersGetOrdersGetGetError =
  GetOrdersGetOrdersGetGetErrors[keyof GetOrdersGetOrdersGetGetErrors];

export type GetOrdersGetOrdersGetGetResponses = {
  /**
   * Response Get Orders Get Orders Get Get
   *
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type GetOrdersGetOrdersGetGetResponse =
  GetOrdersGetOrdersGetGetResponses[keyof GetOrdersGetOrdersGetGetResponses];

export type PostOrderCalcMarginOrderCalcMarginPostData = {
  body: OrderCalcMarginRequest;
  path?: never;
  query?: never;
  url: "/order-calc-margin";
};

export type PostOrderCalcMarginOrderCalcMarginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostOrderCalcMarginOrderCalcMarginPostError =
  PostOrderCalcMarginOrderCalcMarginPostErrors[keyof PostOrderCalcMarginOrderCalcMarginPostErrors];

export type PostOrderCalcMarginOrderCalcMarginPostResponses = {
  /**
   * Successful Response
   */
  200: CalcMarginResponse;
};

export type PostOrderCalcMarginOrderCalcMarginPostResponse =
  PostOrderCalcMarginOrderCalcMarginPostResponses[keyof PostOrderCalcMarginOrderCalcMarginPostResponses];

export type PostOrderCalcProfitOrderCalcProfitPostData = {
  body: OrderCalcProfitRequest;
  path?: never;
  query?: never;
  url: "/order-calc-profit";
};

export type PostOrderCalcProfitOrderCalcProfitPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostOrderCalcProfitOrderCalcProfitPostError =
  PostOrderCalcProfitOrderCalcProfitPostErrors[keyof PostOrderCalcProfitOrderCalcProfitPostErrors];

export type PostOrderCalcProfitOrderCalcProfitPostResponses = {
  /**
   * Successful Response
   */
  200: CalcProfitResponse;
};

export type PostOrderCalcProfitOrderCalcProfitPostResponse =
  PostOrderCalcProfitOrderCalcProfitPostResponses[keyof PostOrderCalcProfitOrderCalcProfitPostResponses];

export type PostOrderCheckOrderCheckPostData = {
  body: TradeRequest;
  path?: never;
  query?: never;
  url: "/order-check";
};

export type PostOrderCheckOrderCheckPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostOrderCheckOrderCheckPostError =
  PostOrderCheckOrderCheckPostErrors[keyof PostOrderCheckOrderCheckPostErrors];

export type PostOrderCheckOrderCheckPostResponses = {
  /**
   * Successful Response
   */
  200: CheckResult;
};

export type PostOrderCheckOrderCheckPostResponse =
  PostOrderCheckOrderCheckPostResponses[keyof PostOrderCheckOrderCheckPostResponses];

export type PostOrderSendOrderSendPostData = {
  body: TradeRequest;
  path?: never;
  query?: never;
  url: "/order-send";
};

export type PostOrderSendOrderSendPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PostOrderSendOrderSendPostError =
  PostOrderSendOrderSendPostErrors[keyof PostOrderSendOrderSendPostErrors];

export type PostOrderSendOrderSendPostResponses = {
  /**
   * Successful Response
   */
  200: TradeResult;
};

export type PostOrderSendOrderSendPostResponse =
  PostOrderSendOrderSendPostResponses[keyof PostOrderSendOrderSendPostResponses];

export type GetPositionsTotalPositionsTotalGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/positions-total";
};

export type GetPositionsTotalPositionsTotalGetResponses = {
  /**
   * Successful Response
   */
  200: TotalResponse;
};

export type GetPositionsTotalPositionsTotalGetResponse =
  GetPositionsTotalPositionsTotalGetResponses[keyof GetPositionsTotalPositionsTotalGetResponses];

export type GetPositionsGetPositionsGetGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Symbol
     *
     * Filter by symbol
     */
    symbol?: string | null;
    /**
     * Group
     *
     * Filter by group pattern
     */
    group?: string | null;
    /**
     * Ticket
     *
     * Filter by ticket
     */
    ticket?: number | null;
  };
  url: "/positions-get";
};

export type GetPositionsGetPositionsGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPositionsGetPositionsGetGetError =
  GetPositionsGetPositionsGetGetErrors[keyof GetPositionsGetPositionsGetGetErrors];

export type GetPositionsGetPositionsGetGetResponses = {
  /**
   * Response Get Positions Get Positions Get Get
   *
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type GetPositionsGetPositionsGetGetResponse =
  GetPositionsGetPositionsGetGetResponses[keyof GetPositionsGetPositionsGetGetResponses];

export type GetHistoryOrdersTotalHistoryOrdersTotalGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
  };
  url: "/history-orders-total";
};

export type GetHistoryOrdersTotalHistoryOrdersTotalGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHistoryOrdersTotalHistoryOrdersTotalGetError =
  GetHistoryOrdersTotalHistoryOrdersTotalGetErrors[keyof GetHistoryOrdersTotalHistoryOrdersTotalGetErrors];

export type GetHistoryOrdersTotalHistoryOrdersTotalGetResponses = {
  /**
   * Successful Response
   */
  200: TotalResponse;
};

export type GetHistoryOrdersTotalHistoryOrdersTotalGetResponse =
  GetHistoryOrdersTotalHistoryOrdersTotalGetResponses[keyof GetHistoryOrdersTotalHistoryOrdersTotalGetResponses];

export type GetHistoryOrdersGetHistoryOrdersGetGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
    /**
     * Group
     *
     * Filter by group pattern
     */
    group?: string | null;
    /**
     * Ticket
     *
     * Filter by ticket
     */
    ticket?: number | null;
  };
  url: "/history-orders-get";
};

export type GetHistoryOrdersGetHistoryOrdersGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHistoryOrdersGetHistoryOrdersGetGetError =
  GetHistoryOrdersGetHistoryOrdersGetGetErrors[keyof GetHistoryOrdersGetHistoryOrdersGetGetErrors];

export type GetHistoryOrdersGetHistoryOrdersGetGetResponses = {
  /**
   * Response Get History Orders Get History Orders Get Get
   *
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type GetHistoryOrdersGetHistoryOrdersGetGetResponse =
  GetHistoryOrdersGetHistoryOrdersGetGetResponses[keyof GetHistoryOrdersGetHistoryOrdersGetGetResponses];

export type GetHistoryDealsTotalHistoryDealsTotalGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
  };
  url: "/history-deals-total";
};

export type GetHistoryDealsTotalHistoryDealsTotalGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHistoryDealsTotalHistoryDealsTotalGetError =
  GetHistoryDealsTotalHistoryDealsTotalGetErrors[keyof GetHistoryDealsTotalHistoryDealsTotalGetErrors];

export type GetHistoryDealsTotalHistoryDealsTotalGetResponses = {
  /**
   * Successful Response
   */
  200: TotalResponse;
};

export type GetHistoryDealsTotalHistoryDealsTotalGetResponse =
  GetHistoryDealsTotalHistoryDealsTotalGetResponses[keyof GetHistoryDealsTotalHistoryDealsTotalGetResponses];

export type GetHistoryDealsGetHistoryDealsGetGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Date From
     *
     * Start date (unix timestamp)
     */
    date_from: number;
    /**
     * Date To
     *
     * End date (unix timestamp)
     */
    date_to: number;
    /**
     * Group
     *
     * Filter by group pattern
     */
    group?: string | null;
    /**
     * Ticket
     *
     * Filter by ticket
     */
    ticket?: number | null;
  };
  url: "/history-deals-get";
};

export type GetHistoryDealsGetHistoryDealsGetGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHistoryDealsGetHistoryDealsGetGetError =
  GetHistoryDealsGetHistoryDealsGetGetErrors[keyof GetHistoryDealsGetHistoryDealsGetGetErrors];

export type GetHistoryDealsGetHistoryDealsGetGetResponses = {
  /**
   * Response Get History Deals Get History Deals Get Get
   *
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type GetHistoryDealsGetHistoryDealsGetGetResponse =
  GetHistoryDealsGetHistoryDealsGetGetResponses[keyof GetHistoryDealsGetHistoryDealsGetGetResponses];

export type GetTradesTradesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/trades";
};

export type GetTradesTradesGetResponses = {
  /**
   * Successful Response
   */
  200: TradesResponse;
};

export type GetTradesTradesGetResponse =
  GetTradesTradesGetResponses[keyof GetTradesTradesGetResponses];

export type GetAccountAccountGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/account";
};

export type GetAccountAccountGetResponses = {
  /**
   * Successful Response
   */
  200: AccountResponse;
};

export type GetAccountAccountGetResponse =
  GetAccountAccountGetResponses[keyof GetAccountAccountGetResponses];

export type GetHistoryHistoryGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * From
     *
     * Start time (unix seconds). Defaults to 24 hours ago.
     */
    from?: number;
    /**
     * To
     *
     * End time (unix seconds). Defaults to now.
     */
    to?: number;
  };
  url: "/history";
};

export type GetHistoryHistoryGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetHistoryHistoryGetError =
  GetHistoryHistoryGetErrors[keyof GetHistoryHistoryGetErrors];

export type GetHistoryHistoryGetResponses = {
  /**
   * Successful Response
   */
  200: HistoryResponse;
};

export type GetHistoryHistoryGetResponse =
  GetHistoryHistoryGetResponses[keyof GetHistoryHistoryGetResponses];

export type GetSymbolsSymbolsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/symbols";
};

export type GetSymbolsSymbolsGetResponses = {
  /**
   * Successful Response
   */
  200: SymbolsResponse;
};

export type GetSymbolsSymbolsGetResponse =
  GetSymbolsSymbolsGetResponses[keyof GetSymbolsSymbolsGetResponses];

export type GetHealthHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type GetHealthHealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type GetHealthHealthGetResponse =
  GetHealthHealthGetResponses[keyof GetHealthHealthGetResponses];
